-- Add skill rules fields for intelligent skill suggestion
-- keywords: for keyword matching in hooks
-- hint: guidance for Claude when skill is suggested
-- is_general: always show in skill hints (not keyword-dependent)

ALTER TABLE zeude_skills
  ADD COLUMN IF NOT EXISTS keywords text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS hint text DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_general boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_command boolean DEFAULT false;

-- Index for efficient general skill queries
CREATE INDEX IF NOT EXISTS idx_skills_is_general ON zeude_skills (is_general) WHERE is_general = true;

-- Index for filtering out commands in skill-rules API
CREATE INDEX IF NOT EXISTS idx_skills_is_command ON zeude_skills (is_command) WHERE is_command = false;

COMMENT ON COLUMN zeude_skills.keywords IS 'Keywords for matching user prompts (generated by LLM)';
COMMENT ON COLUMN zeude_skills.hint IS 'Guidance for Claude when this skill is suggested (generated by LLM)';
COMMENT ON COLUMN zeude_skills.is_general IS 'If true, always show in skill hints regardless of keyword match';
COMMENT ON COLUMN zeude_skills.is_command IS 'If true, skill has allowed-tools (command) - excluded from skill-rules';
