#!/bin/bash
# Zeude Uninstallation Script
# Completely removes Zeude and restores original claude setup
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

ZEUDE_DIR="$HOME/.zeude"
CLAUDE_DIR="$HOME/.claude"
CLAUDE_JSON="$HOME/.claude.json"

printf "${RED}Zeude Uninstaller${NC}\n"
echo "======================================"
echo ""
printf "${YELLOW}This will remove:${NC}\n"
echo "  - Zeude shim and config (~/.zeude/)"
echo "  - Zeude-installed hooks (~/.claude/hooks/)"
echo "  - Zeude-managed MCP servers (~/.claude.json)"
echo "  - /zeude skill (~/.claude/commands/zeude.md)"
echo "  - PATH configuration from shell rc files"
echo ""

# Confirm uninstall
read -p "Are you sure you want to uninstall Zeude? (y/N) " -n 1 -r < /dev/tty
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Uninstall cancelled."
    exit 0
fi

echo ""

# 1. Remove Zeude hooks from ~/.claude/hooks/
echo -n "Removing Zeude hooks... "
HOOKS_REMOVED=0
if [ -f "$ZEUDE_DIR/managed-hooks.json" ] && command -v jq &> /dev/null; then
    # Read managed hooks and remove them
    MANAGED_HOOKS=$(jq -r '.hooks[]' "$ZEUDE_DIR/managed-hooks.json" 2>/dev/null || true)
    for hook in $MANAGED_HOOKS; do
        if [ -f "$hook" ]; then
            rm -f "$hook"
            HOOKS_REMOVED=$((HOOKS_REMOVED + 1))
        fi
    done
fi

# Fallback: remove all hooks with "Auto-generated by Zeude" comment
if [ -d "$CLAUDE_DIR/hooks" ]; then
    while IFS= read -r hook; do
        if [ -n "$hook" ] && grep -q "Auto-generated by Zeude" "$hook" 2>/dev/null; then
            rm -f "$hook"
            HOOKS_REMOVED=$((HOOKS_REMOVED + 1))
        fi
    done < <(find "$CLAUDE_DIR/hooks" -type f \( -name "*.sh" -o -name "*.py" -o -name "*.js" \) 2>/dev/null || true)
fi

if [ $HOOKS_REMOVED -gt 0 ]; then
    printf "${GREEN}Removed $HOOKS_REMOVED hooks${NC}\n"
else
    printf "${YELLOW}No hooks found${NC}\n"
fi

# 2. Clean up ~/.claude/settings.json (remove Zeude hook registrations)
echo -n "Cleaning settings.json... "
SETTINGS_FILE="$CLAUDE_DIR/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
    if command -v jq &> /dev/null; then
        # Remove hooks that contain ".claude/hooks/" in command (Zeude hooks)
        TMP_SETTINGS=$(mktemp)
        if jq '
          if .hooks then
            .hooks = (
              .hooks | to_entries | map(
                .value = [.value[] | select(
                  (.hooks // []) | all(.command | contains(".claude/hooks/") | not)
                )]
              ) | map(select(.value | length > 0)) | from_entries
            )
          else .
          end
        ' "$SETTINGS_FILE" > "$TMP_SETTINGS" 2>/dev/null; then
            mv "$TMP_SETTINGS" "$SETTINGS_FILE"
            printf "${GREEN}OK${NC}\n"
        else
            rm -f "$TMP_SETTINGS"
            printf "${YELLOW}Failed (jq error)${NC}\n"
        fi
    else
        printf "${YELLOW}SKIPPED (jq not installed)${NC}\n"
    fi
else
    printf "${YELLOW}Not found${NC}\n"
fi

# 3. Clean up ~/.claude.json (remove Zeude-managed MCP servers)
echo -n "Cleaning claude.json... "
if [ -f "$CLAUDE_JSON" ] && [ -f "$ZEUDE_DIR/managed-keys.json" ]; then
    if command -v jq &> /dev/null; then
        # Read managed keys
        MANAGED_KEYS=$(jq -r '.keys[]' "$ZEUDE_DIR/managed-keys.json" 2>/dev/null || true)

        if [ -n "$MANAGED_KEYS" ]; then
            TMP_CLAUDE=$(mktemp)
            cp "$CLAUDE_JSON" "$TMP_CLAUDE"

            # Remove each managed key from mcpServers
            for key in $MANAGED_KEYS; do
                if jq "del(.mcpServers.\"$key\")" "$TMP_CLAUDE" > "${TMP_CLAUDE}.new" 2>/dev/null; then
                    mv "${TMP_CLAUDE}.new" "$TMP_CLAUDE"
                fi
            done

            mv "$TMP_CLAUDE" "$CLAUDE_JSON"
            printf "${GREEN}OK${NC}\n"
        else
            printf "${YELLOW}No managed servers${NC}\n"
        fi
    else
        printf "${YELLOW}SKIPPED (jq not installed)${NC}\n"
    fi
else
    printf "${YELLOW}Not found${NC}\n"
fi

# 4. Remove /zeude skill
echo -n "Removing /zeude skill... "
SKILL_FILE="$CLAUDE_DIR/commands/zeude.md"
if [ -f "$SKILL_FILE" ]; then
    rm -f "$SKILL_FILE"
    printf "${GREEN}OK${NC}\n"
else
    printf "${YELLOW}Not found${NC}\n"
fi

# 5. Remove PATH from shell config
echo -n "Removing PATH configuration... "
PATH_REMOVED=false

for RC_FILE in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.profile"; do
    if [ -f "$RC_FILE" ] && grep -q "zeude" "$RC_FILE" 2>/dev/null; then
        # Create backup
        cp "$RC_FILE" "${RC_FILE}.zeude-backup"

        # Remove zeude lines (macOS and Linux compatible)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' '/# Zeude/d' "$RC_FILE"
            sed -i '' '/zeude\/bin/d' "$RC_FILE"
        else
            sed -i '/# Zeude/d' "$RC_FILE"
            sed -i '/zeude\/bin/d' "$RC_FILE"
        fi
        PATH_REMOVED=true
    fi
done

if [ "$PATH_REMOVED" = true ]; then
    printf "${GREEN}OK${NC}\n"
else
    printf "${YELLOW}Not found${NC}\n"
fi

# 6. Remove ~/.zeude directory (last, as we need managed-*.json files above)
echo -n "Removing Zeude directory... "
if [ -d "$ZEUDE_DIR" ]; then
    rm -rf "$ZEUDE_DIR"
    printf "${GREEN}OK${NC}\n"
else
    printf "${YELLOW}Not found${NC}\n"
fi

# Remove empty hook directories
if [ -d "$CLAUDE_DIR/hooks" ]; then
    find "$CLAUDE_DIR/hooks" -type d -empty -delete 2>/dev/null || true
fi

# Summary
echo ""
printf "${GREEN}Uninstall complete!${NC}\n"
echo "======================================"
echo ""
echo "Zeude has been removed from your system."
echo "The original claude command is now restored."
echo ""
printf "${YELLOW}Next steps:${NC}\n"
printf "  1. Restart your shell or run: ${BLUE}source ~/.zshrc${NC}\n"
printf "  2. Run '${BLUE}claude${NC}' to use the original Claude CLI\n"
echo ""
echo "To reinstall Zeude later:"
printf "  ${BLUE}curl -fsSL https://your-dashboard-url/releases/install.sh | ZEUDE_AGENT_KEY=zd_xxx bash${NC}\n"
